image: node:9

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - public

pages:
  stage: deploy
  script:
  - npm run pages
  artifacts:
    paths:
      - public
  only:
  - master