image: node:21

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run pages
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
  - echo 'hi'
  artifacts:
    paths:
      - public
  only:
  - master