version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  
  build:
    commands:
      - npm run build
      - npm run pages
      - ./deploy/create-config-files.sh

artifacts:
  secondary-artifacts:
    siteFiles:
      base-directory: public
      files:
        - "**/*"
    buildResults:
      discard-paths: yes
      files:
        - "deploy/icons.template.yml"
        - "deploy/dns.template.yml"
        - "*.config.json"      