Parameters:
  DomainName:
    Type: String
    Description: Domain name to serve icons from

  HostedZoneId:
    Type: String
    Description: ID of the hosted zone to add DNS records to

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudfrontIdentity.S3CanonicalUserId
            Action: 
              - s3:ListBucket
              - s3:GetObject
            Resource: 
              - !Sub arn:aws:s3:::${Bucket}
              - !Sub arn:aws:s3:::${Bucket}/*

  CloudfrontIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin access identity for Cythral Icons

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      Tags: []
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Comment: CloudFront distribution for Cythral Icons
        Enabled: true
        PriceClass: PriceClass_100
        DefaultRootObject: index.html
        ViewerCertificate: 
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          TargetOriginId: primary
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - OPTIONS
            - GET
          ForwardedValues:
            QueryString: true
        Origins:
          - Id: primary
            DomainName: !GetAtt Bucket.DomainName
            S3OriginConfig: 
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudfrontIdentity}

  CertificateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub 
                - arn:aws:iam::${AccountId}:role/cfn-resources-CertificateRole-H12NWXVKTFJA
                - AccountId: !ImportValue cfn-utilities:MasterAccountId
  
  CertificatePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: acm:*
            Resource: "*"
      Roles:
        - !Ref CertificateRole

  Certificate:
    Type: Custom::Certificate
    DependsOn:
      - CertificatePolicy
    Properties:
      ServiceToken: !Sub 
        - arn:aws:lambda:${AWS::Region}:${MasterAccountId}:function:Certificate
        - MasterAccountId: !ImportValue cfn-utilities:MasterAccountId
      DomainName: !Ref DomainName
      ValidationType: DNS
      HostedZoneId: !Ref HostedZoneId
      CreationRoleArn: !GetAtt CertificateRole.Arn

Outputs:
  DomainName:
    Value: !Ref DomainName
    Description: Domain name to put this deployment of icons under
    Export:
      Name: !Sub ${AWS::StackName}:DomainName

  CloudfrontDomainName:
    Value: !GetAtt CloudfrontDistribution.DomainName
    Description: Domain name of the cloudfront distribution to CNAME
    Export:
      Name: !Sub ${AWS::StackName}:CloudfrontDomainName