Parameters:
  DomainName:
    Type: String
    Description: Domain name to serve icons from

  HostedZoneId:
    Type: String
    Description: ID of the hosted zone to add DNS records to

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
  
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudfrontIdentity.S3CanonicalUserId
            Action: 
              - s3:ListBucket
              - s3:GetObject
            Resource: 
              - !Sub arn:aws:s3:::${Bucket}
              - !Sub arn:aws:s3:::${Bucket}/*

  CloudfrontIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin access identity for Cythral Icons

  CertificateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              AWS: !Sub 
                - arn:aws:iam::${AccountId}:role/cfn-resources-CertificateRole-H12NWXVKTFJA
                - AccountId: !ImportValue cfn-utilities:MasterAccountId
  
  CertificatePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: acm:*
            Resource: "*"
      Roles:
        - !Ref CertificateRole

  Certificate:
    Type: Custom::Certificate
    Properties:
      ServiceToken: !Sub 
        - arn:aws:lambda:${AWS::Region}:${MasterAccountId}:function:Certificate
        - MasterAccountId: !ImportValue cfn-utilities:MasterAccountId
      DomainName: !Ref DomainName
      ValidationType: DNS
      HostedZoneId: !Ref HostedZoneId
      CreationRoleArn: !GetAtt CertificateRole.Arn

Outputs:
  BucketName:
    Value: !Ref DomainName
    Description: Name of the bucket that icons is deployed to in this environment
    Export:
      Name: !Sub ${AWS::StackName}:BucketName